name:                middlesex
version:             0.1.0.0
github:              "mrehayden1/middlesex"
license:             None
author:              "Matthew Hayden"
maintainer:          "mrehayden@gmail.com"
copyright:           "2024 Matthew Hayden"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mrehayden1/middlesex#readme>

dependencies:
- base >= 4.7 && < 5
- GLFW-b
- GPipe
- GPipe-GLFW
- dependent-sum
- exception-transformers
- mtl
- reflex
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- ConstraintKinds
- FlexibleContexts
- RecordWildCards
- ScopedTypeVariables

executables:
  middlesex-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
